import { useEffect, useState } from 'react'
import './teacher-dashboard.css'
import TeacherDashboardView from './TeacherDashboard'

const api = async (path, options = {}) => {
  const token = localStorage.getItem('sfs_token')
  const response = await fetch(`/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.detail || 'Something went wrong')
  return data
}

function Auth({ onLogin }) {
  const [role, setRole] = useState('student'); const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { const data = await api(`/auth/${mode}/${role}`, { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('sfs_token', data.token); onLogin(data.user) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  const update = (key) => (event) => setForm({ ...form, [key]: event.target.value })
  return <main className="auth-page"><section className="auth-intro"><div className="brand-mark">sf</div><p className="eyebrow">STUDENT FEEDBACK SYSTEM</p><h1>Make every piece of work a step forward.</h1><p className="intro-copy">Upload work, receive thoughtful AI feedback, and keep progress visible from first draft to final answer.</p><div className="signal"><span /> AI-powered review <span /> teacher-led progress</div></section><section className="auth-card"><div className="role-switch"><button className={role === 'student' ? 'active' : ''} onClick={() => setRole('student')}>Student</button><button className={role === 'teacher' ? 'active' : ''} onClick={() => setRole('teacher')}>Teacher</button></div><div className="form-heading"><p className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'GET STARTED'}</p><h2>{mode === 'login' ? `Sign in as a ${role}` : `Create your ${role} account`}</h2><p>{mode === 'login' ? 'Pick up where you left off.' : 'A focused space for better learning.'}</p></div><form onSubmit={submit}>{mode === 'signup' && <label>Full name<input required value={form.name} onChange={update('name')} placeholder="Alex Morgan" /></label>}<label>Email address<input required type="email" value={form.email} onChange={update('email')} placeholder="you@school.edu" /></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={update('password')} placeholder="8+ characters" /></label>{error && <p className="error">{error}</p>}<button className="primary-button" disabled={loading}>{loading ? 'Opening your workspace...' : mode === 'login' ? 'Sign in' : 'Create account'} <span>→</span></button></form><p className="auth-toggle">{mode === 'login' ? 'New here?' : 'Already have an account?'} <button onClick={() => { setMode(mode === 'login' ? 'signup' : 'login'); setError('') }}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p></section></main>
}

function Header({ user, onLogout }) { return <header className="app-header"><div className="brand"><div className="brand-mark small">sf</div><span>student feedback</span></div><div className="user-menu"><span className="avatar">{user.name.slice(0, 1).toUpperCase()}</span><span className="user-name">{user.name}</span><button onClick={onLogout}>Sign out</button></div></header> }

function StudentHome({ user }) {
  const [file, setFile] = useState(null); const [status, setStatus] = useState(''); const [grading, setGrading] = useState(null)
  const upload = async () => { if (!file) return; setStatus('Reviewing your work...'); setGrading(null); const body = new FormData(); body.append('file', file); try { const response = await fetch('/api/upload', { method: 'POST', headers: { Authorization: `Bearer ${localStorage.getItem('sfs_token')}` }, body }); const result = await response.json(); if (!response.ok) throw new Error(result.detail || 'Upload failed'); setGrading(result.grading); setStatus('Review complete') } catch (err) { setStatus(err.message) } }
  return <main className="workspace"><div className="page-top"><div><p className="eyebrow">STUDENT WORKSPACE</p><h1>Good to see you, {user.name.split(' ')[0]}.</h1><p className="muted">Share a piece of work and get a clear next step.</p></div><div className="date-chip">● Learning in progress</div></div><section className="upload-grid"><div className="upload-panel"><div className="section-kicker">01 <span>SUBMIT YOUR WORK</span></div><h2>Turn a page into progress.</h2><p className="muted">Upload a clear photo of a question and your answer. Our AI will read it, check it, and explain what to try next.</p><label className={`dropzone ${file ? 'has-file' : ''}`}><input type="file" accept="image/*" onChange={(e) => setFile(e.target.files[0] || null)} /><span className="upload-icon">↥</span><strong>{file ? file.name : 'Drop an image here'}</strong><small>{file ? 'Ready to review' : 'or click to browse · PNG, JPG up to 10MB'}</small></label><button className="primary-button upload-button" disabled={!file || status === 'Reviewing your work...'} onClick={upload}>{status === 'Reviewing your work...' ? 'Analyzing image...' : 'Get AI feedback'} <span>→</span></button>{status && !['Review complete', 'Reviewing your work...'].includes(status) && <p className="error">{status}</p>}</div><div className="how-panel"><div className="section-kicker">02 <span>WHAT YOU'LL GET</span></div>{[['01', 'Read', 'Text is extracted from your page.'], ['02', 'Understand', 'Your answer is checked against the question.'], ['03', 'Improve', 'Feedback points you toward the next attempt.']].map(([number, title, text]) => <div className="benefit" key={number}><b>{number}</b><div><strong>{title}</strong><p>{text}</p></div></div>)}</div></section>{grading && <section className="feedback-result"><div className="result-head"><div><p className="eyebrow">AI REVIEW · JUST NOW</p><h2>Your feedback is ready.</h2></div><div className={`score-badge ${grading.is_correct ? 'correct' : 'needs-work'}`}>{grading.is_correct ? 'Correct' : 'Keep going'}</div></div><div className="feedback-body">{[['QUESTION', grading.question || 'Question not detected'], ['YOUR ANSWER', grading.answer || 'Answer not detected'], ['NEXT STEP', grading.feedback]].map(([label, text], index) => <div className={index === 2 ? 'feedback-note' : ''} key={label}><p className="label">{label}</p><p>{text}</p></div>)}</div></section>}</main>
}

function TeacherDashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState('')
  useEffect(() => { api('/teacher/dashboard').then(setData).catch((err) => setError(err.message)) }, [])
  if (error) return <main className="workspace"><p className="error">{error}</p></main>
  if (!data) return <div className="loading">Loading dashboard...</div>
  const cards = [['students', 'Total students', 'active learners'], ['uploads', 'Student uploads', 'pieces submitted'], ['images', 'Uploaded images', 'pages reviewed'], ['feedback', 'AI feedback', 'reviews completed'], ['average_score', 'Average score', 'across submissions']]
  return <main className="workspace"><div className="page-top"><div><p className="eyebrow">TEACHER DASHBOARD</p><h1>See learning take shape.</h1><p className="muted">A clear view of your students' work and momentum.</p></div><div className="date-chip">● Live overview</div></div><div className="stats-grid">{cards.map(([key, title, detail]) => <article className="stat-card" key={key}><p>{title}</p><strong>{data.stats[key]}{key === 'average_score' ? '%' : ''}</strong><small>{detail}</small></article>)}</div><section className="activity-section"><div className="section-title"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Latest student work</h2></div><span>{data.recent.length} recent</span></div>{data.recent.length ? <div className="activity-list">{data.recent.map((item) => <div className="activity-row" key={item.id}><div className="file-icon">▧</div><div className="activity-student"><small>STUDENT</small><strong>{item.student}</strong><span>{item.created_at ? new Date(item.created_at).toLocaleDateString() : 'Recently'}</span></div><div className="activity-upload"><small>UPLOADED</small><strong>{item.filename}</strong></div><div className="activity-feedback"><small>AI FEEDBACK</small><span>{item.feedback}</span></div><div className={`mini-score ${item.score === 100 ? 'correct' : ''}`}>{item.score}%</div></div>)}</div> : <div className="empty-state">Student uploads will appear here once work starts coming in.</div>}</section></main>
}

function App() { const [user, setUser] = useState(null); const [checking, setChecking] = useState(true); useEffect(() => { if (localStorage.getItem('sfs_token')) api('/me').then(setUser).catch(() => localStorage.removeItem('sfs_token')).finally(() => setChecking(false)); else setChecking(false) }, []); const logout = () => { localStorage.removeItem('sfs_token'); setUser(null) }; if (checking) return <div className="loading">Preparing your workspace...</div>; if (!user) return <Auth onLogin={setUser} />; return <><Header user={user} onLogout={logout} />{user.role === 'teacher' ? <TeacherDashboardView /> : <StudentHome user={user} />}</> }

export default App